[hosts]
app = "https://the-day-of-reckoning-communication-suite-5c19ff-95-217-110-46.traefik.me"
api = "https://the-day-of-reckoning-communication-suite-5c19ff-95-217-110-46.traefik.me/api"
events = "wss://the-day-of-reckoning-communication-suite-5c19ff-95-217-110-46.traefik.me/ws"
autumn = "https://the-day-of-reckoning-communication-suite-5c19ff-95-217-110-46.traefik.me/autumn"
january = "https://the-day-of-reckoning-communication-suite-5c19ff-95-217-110-46.traefik.me/january"

[pushd.vapid]
private_key = ""
public_key = ""

[files]
encryption_key = "ILlJw7pjlKqqWZKnE7vGG9XYfhQBE9zF/3G2cNcgLyc="
